### ISSUE TITLE
Release 1.0?

### ISSUE THREAD

**Issue by tisonkun** [swsnr/gethostname.rs#19]
Thanks for this wonderful crate! I find it easy to use and robust.

@swsnr is there any blocker or pending task before 1.0? I find it more confident to use a crate beyond 1.0, not sure if anything make this crate yet to be stable now.

**Comment by tisonkun** [comment]
See also https://0ver.org/.

But if you as the maintainer like this flavor, it should be fine.

**Comment by swsnr** [comment]
I'm not sure what to make of this link. Is this some kind of crusade?

I mean this crate exports a single function whose interfaces comes from like 40 years ago. It's not like there are going to be huge changes still... 

If it helps I can make a new release with a 1 in front, but what difference would that make?  It'd still be the same code, and it'd still bear no commitment from me 🤷

No offence but I'm not sure if I'm supposed to take this seriously...

**Comment by tisonkun** [comment]
> If it helps I can make a new release with a 1 in front, but what difference would that make? It'd still be the same code, and it'd still bear no commitment from me 🤷

This is true. And I feel that somehow cargo treat 0.x as a formal version encourages maintainer to use its rule as:

* 0.X.Y where modifying Y is to make a non-break release (as changing minor version or patch version beyond 1.0); and
* modifying X is to make a break release (as bumping major version beyond 1.0).

Closed as won't do. It's fine to stay in your flavor.
